---
title: "wordbank"
output: html_document
---

Libraries
```{r}
  library(broom)
  library(purrr)
  library(readr)
  library(ggplot2)
  library(dplyr)
  library(tidyr)
  library(wordbankr)
  library(stringr)
  library(feather)
  library(lme4)
  library(boot)
  library(langcog)
  library(ggthemes)
  library(nlme)
  #library(rwebppl)
  library(jsonlite)
  library(Hmisc)
  library(poweRlaw)
  library(HDInterval)
  library(kableExtra)
```

Import helper functions and probabilstic models

```{r}
#Load helper functions
source(paste(getwd(),"/helper_functions/all_helper.r",sep = ""), chdir = T)
#Load probabilsitic models
source(paste(getwd(),"/models/all_models.r",sep = ""), chdir = T)
```
```{r}
trim_all_unilemma<-function(unilemma_list){
  unilemma_list<- unilemma_list %>%
    mutate(uni_lemma=gsub(" \\s*\\([^\\)]+\\)","", uni_lemma)) %>%
    mutate(uni_lemma=gsub("[*].*$","", uni_lemma)) %>%
    filter(!is.na(uni_lemma))
  return(unilemma_list)
}
```



Load data and pre-process
```{r}
#languages = c("Croatian","Danish","English (American)", "French (Quebecois)", "Italian", "Norwegian", "Russian", "Spanish (Mexican)", "Swedish", "Turkish")
languages = c("English (American)")
admins <- get_administration_data() %>%
  select(data_id, age, language, form) %>%
  filter(language %in% languages)
items <- get_item_data() %>%
  filter(type == "word", lexical_class == "nouns") %>%
  filter(language %in% languages)
items_by_inst <- split(items, paste(items$language, items$form, sep = "_"))
get_inst_data <- function(inst_items) {
  inst_lang <- unique(inst_items$language)
  inst_form <- unique(inst_items$form)
  inst_admins <- filter(admins, language == inst_lang, form == inst_form)
  get_instrument_data(language = inst_lang ,
                      form = inst_form,
                      administrations = inst_admins,
                      items = inst_items$item_id,
                      iteminfo = inst_items
                      ) %>%
    filter(!is.na(age)) %>%
    mutate(produces = !is.na(value) & value == "produces",
           understands = !is.na(value) & (value == "understands" | value == "produces")) %>%
    select(-value) %>%
    gather(measure, value, produces, understands) %>%
    filter((measure == "understands" & form == "WG") | (measure == "produces" & form == "WS") ) %>%
    mutate(language = inst_lang,
           form = inst_form)
    
}
data_raw <- map(items_by_inst, get_inst_data) 
  
data_all <- bind_rows(data_raw) %>%
  rename(item = num_item_id) %>%
  #Run the entire list of words with code
  group_by(language, form, measure, category,
             lexical_category, lexical_class, uni_lemma,  item, definition, 
             age) %>%
  summarise(num_true = sum(value, na.rm = TRUE),
              num_false = n() - num_true,
              prop = mean(value, na.rm = TRUE)) %>%
  ungroup() %>%
  dplyr::filter(form == "WS") %>%
  trim_all_unilemma() %>%
  group_by(language, form, measure, category,
             lexical_category, lexical_class, uni_lemma,  item, definition, 
             age)

#feather::write_feather(data_all, "data_all.feather")

#I am taking out measure to keep only produce
#data_all <- feather::read_feather("all_data.feather") 
#data_all <- dplyr::filter(data_all, language == "English (American)")
```

```{r}
unique_items <- lapply(split(data_all$uni_lemma, data_all$category), function(x) sort(unique(x)) )
```

```{r}
unique_items.df <- plyr::ldply(unique_items, rbind)
write.csv(unique_items.df, "wb_nouns.csv", na="")
```
